### ISSUE TITLE
#Math

### ISSUE THREAD

**Issue by lilongcnc** [YouXianMing/Animations#2]
作者您好,我想请问下Math.h文件中的那些计算方法?是什么算法.是您自己写的吗?还是和您底下那些链接一下,是参考别人的呢?那一块,我不理解.我自己再做UISCrollView的视觉差动画那个

**Comment by YouXianMing** [comment]
其实是一元一次方程组，Y = k X + b，给出两个点计算出了 k 以及 b，因为大部分相关变化的关系都是线性的（比方说UIScrollView的偏移量为0的时候某个控件的透明度为1，而当UIScrollView的偏移量为400的时候，某个控件的透明度为0，很明显，他们是一个线性关系，一条直线而已），所以就抽象出了计算一元一次方程的类，如果每次都单独写的话会浪费性能，希望能帮到你。

**Comment by lilongcnc** [comment]
感谢您的回复,您上边说的我明白了.还想请问下,那如何计算出" k 以及 b"这里两个参数的值的算法逻辑,是您自己定义的吗?额......我看您源码计算方法中calculateConstant:这个方法,四个参数算出了k,b,:
CGFloat calculateSlope(CGFloat x1, CGFloat y1, CGFloat x2, CGFloat y2) {//Slope:边坡

```
if (x2 == x1) {

    return 0;
}

return (y2 - y1) / (x2 - x1);
```

}

CGFloat calculateConstant(CGFloat x1, CGFloat y1, CGFloat x2, CGFloat y2) {//Constant:常数

```
if (x2 == x1) {

    return 0;
}

return (y1*(x2 - x1) - x1*(y2 - y1)) / (x2 - x1);
```

}
这个是一元一次方程公式就是这样计算的吗? 毕业没做过动画......代数都还给老师了.......

**Comment by YouXianMing** [comment]
自己用方程组算的......   y1 = k X1 + b   y2 = k X2 + b ，然后计算出 k 与 b 的值。

**Comment by lilongcnc** [comment]
这次明白了!!!非常谢谢您!百度了下,找到了类似的计算题,真的是数学全还给老师了....
