### ISSUE TITLE
当Push到某些动画展示的控制器时，CPU占用率到达了100%以上

### ISSUE THREAD

**Issue by jniosdeveloper** [YouXianMing/Animations#20]
当Push到某些动画展示的控制器时，CPU占用率到达了100%以上，比如当我去看35的震动效果，pop到首页，控制台显示VC被释放，但是CPU此时占用率到了100%以上了，应该有循环引用的情况。我还没发现该问题的原因，希望作者有时间也可以查看一下。

**Comment by YouXianMing** [comment]
Fix
