### ISSUE TITLE
运行报错，删掉第一个nullable才跑起来

### ISSUE THREAD

**Issue by Huang-Libo** [YouXianMing/Animations#5]
![image](https://cloud.githubusercontent.com/assets/12227130/16705319/3f77686e-45b8-11e6-9755-51645de18f7f.png)

**Comment by YouXianMing** [comment]
能说一下是哪个地方的代码么

**Comment by YouXianMing** [comment]
你需要用最新稳定的Xcode版本(Xcode Version 7.3.1 (7D1014))来运行程序.

**Comment by Huang-Libo** [comment]
@YouXianMing 
TapDrawImageView.m
我用的Xcode 8.0-Beta。

**Comment by YouXianMing** [comment]
我简单修复了一下, 出了稳定版本的 Xcode 8.0 后再解决这些问题.
