### ISSUE TITLE
Xcode8.0,iOS10，手势返回上一个控制器，全白

### ISSUE THREAD

**Issue by Ryan0520** [YouXianMing/Animations#6]
Xcode8.0,iOS10，手势返回上一个控制器，界面全白。

**Comment by YouXianMing** [comment]
太忙了,暂时屏蔽了返回手势,有空了再改.

**Comment by Ryan0520** [comment]
里面的动画都好赞啊！

**Comment by YouXianMing** [comment]
😄

**Comment by Ryan0520** [comment]
@YouXianMing 学习一下那个scrollView的视差效果，可以说一下原理是什么吗？好像现在《UC客户端》上面浏览图片的时候有这种效果

**Comment by Ryan0520** [comment]
@YouXianMing 主要是看不懂 `MATHPoint pointA; MATHPoint pointB;`两个点
