### ISSUE TITLE
第55个不规则GridCell问题

### ISSUE THREAD

**Issue by whqfor** [YouXianMing/Animations#9]
请问：这个效果是不是对图片大小格式有要求，只能只不规则吗，，当传入相同大小的图片时，最后一个cell的和倒数第二个重叠在了一起，不同尺寸的则正常。

![Uploading 11.png…]()

**Comment by whqfor** [comment]
<img width="372" alt="11" src="https://cloud.githubusercontent.com/assets/12791878/22879035/0b3c0792-f217-11e6-89e1-3e52c2b7c752.png">

**Comment by YouXianMing** [comment]
试了下,确实会出现这个问题,原因未知.......建议你直接用UICollectionView封装一个规则的,要比这个简单得多,抱歉呢.

**Comment by YouXianMing** [comment]
你用 "47. 水平方向的瀑布流" 试试,你将那个的行数设置成1就行了,应该没有问题.
